### PR TITLE
Preparation for OpenUPM

### PR DESCRIPTION
**Pull request by IvanMurzak**
- refactored folders structure
- changed dependencies (removed Jobs because it is build-in in Unity editor)
- updated gitignore
- updated package name for supportable by OpenUPM

### CODE REVIEW

**Comment by nixonyh** [comment]
Hey as discussed, I don't think this package format is suitable for Util package.

**Comment by IvanMurzak** [comment]
Folders structure restored. And diff is minimized

**Comment by nixonyh** [comment]
Thanks, I will take a look on the diffs and make a separate commit to match necessary changes. Since it will be a lot of unnecessary commits if merged. Hope you understand. Appreciate your help.

**Comment by IvanMurzak** [comment]
@nixon-voxell  There is a "squash commit" thing, which can be used to make the merge as a single commit

**Comment by nixonyh** [comment]
ok I will try that

**Pull request merged**
